# Generated by Django 4.2.2 on 2023-08-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='followed_user_id',
            new_name='followed_users',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='user_id',
            new_name='user',
        ),
    ]
