# Generated by Django 4.2.2 on 2023-09-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_likes_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
