# Generated by Django 4.2.2 on 2023-07-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_rename_passengers_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='flight',
            new_name='flights',
        ),
    ]
